name: ad_integration_example
description: A Flutter project demonstrating integration with various ad SDKs.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^2.0.0
  appodeal_flutter: ^1.0.0
  unity_ads: ^1.0.0
  startio: ^1.0.0
  inmobi_sdk: ^1.0.0
  yandex_mobile_ads: ^1.0.0

flutter:
  uses-material-design: true
